### PR TITLE
feat: cache root cypress folder

### PR DESCRIPTION
**Pull request by cerdfied**
# Description

Update in Cypress requires caching of ~/cache/Cypress folder for tests to run in CircleCI

Screenshot 2023-08-29 at 11 28 46

# Checklist:

- [x] My branch has been rebased onto the latest commit on main (don't merge main into your branch)
- [x] My commit messages are [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), for example: `feat(circleci): add support for nightly workflows`, `fix: set Heroku app name for staging apps too`

### CODE REVIEW

**Review by ivomurrell — CHANGES_REQUESTED** [review]
you need to use the [cypress image](https://hub.docker.com/r/cypress/included) which has the cypress binary preinstalled; this cache can be deleted at any time and Cypress will fail as a result. (cypress shouldn't really save itself in the cache directory seeing as it throws an error when the cache doesn't exist...)

Tool Kit should be setting this up automatically, let me see what's going wrong...

**Comment by ivomurrell** [comment]
oooof this never got documented: you need to add a `cypressImage` option to the `circleci` plugin to get cypress working. the best documentation available is on this slack thread: https://financialtimes.slack.com/archives/C3TJ6KXEU/p1678178035690449?thread_ts=1677860469.123709&cid=C3TJ6KXEU. there's a [ticket](https://financialtimes.atlassian.net/browse/CPP-1333) to improve this but it's fallen into the backlog 😬

**Comment by cerdfied** [comment]
> oooof this never got documented: you need to add a `cypressImage` option to the `circleci` plugin to get cypress working. the best documentation available is on this slack thread: https://financialtimes.slack.com/archives/C3TJ6KXEU/p1678178035690449?thread_ts=1677860469.123709&cid=C3TJ6KXEU. there's a [ticket](https://financialtimes.atlassian.net/browse/CPP-1333) to improve this but it's fallen into the backlog 😬

ahh yess got it thanks will take a look!

**Comment by cerdfied** [comment]
no longer needed

**Pull request closed without merging**
