### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 3.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/backend-app: 3.1.24</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.11 to ^3.0.12
</details>

<details><summary>@dotcom-tool-kit/backend-heroku-app: 3.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^3.2.8 to ^3.2.9
    * @dotcom-tool-kit/heroku bumped from ^3.3.14 to ^3.3.15
    * @dotcom-tool-kit/node bumped from ^3.3.8 to ^3.3.9
    * @dotcom-tool-kit/npm bumped from ^3.2.2 to ^3.2.3
</details>

<details><summary>@dotcom-tool-kit/backend-serverless-app: 3.0.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^3.2.8 to ^3.2.9
    * @dotcom-tool-kit/node bumped from ^3.3.8 to ^3.3.9
    * @dotcom-tool-kit/npm bumped from ^3.2.2 to ^3.2.3
    * @dotcom-tool-kit/serverless bumped from ^2.2.12 to ^2.2.13
</details>

<details><summary>@dotcom-tool-kit/circleci: 5.3.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/circleci-deploy: 3.2.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^5.3.8 to ^5.3.9
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 3.1.24</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^3.2.8 to ^3.2.9
    * @dotcom-tool-kit/heroku bumped from ^3.3.14 to ^3.3.15
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 5.2.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
    * @dotcom-tool-kit/circleci bumped from ^5.3.8 to ^5.3.9
    * @dotcom-tool-kit/npm bumped from ^3.2.2 to ^3.2.3
</details>

<details><summary>@dotcom-tool-kit/component: 4.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-npm bumped from ^5.2.11 to ^5.2.12
    * @dotcom-tool-kit/npm bumped from ^3.2.2 to ^3.2.3
</details>

<details><summary>create: 3.4.0</summary>

### Features

* **create:** add option to add .toolkitstate to gitignore ([bfb1b82](https://github.com/Financial-Times/dotcom-tool-kit/commit/bfb1b824bbf6cd489bba610d0e99845988ea6023))
* **create:** add option to remove ESLint config from gitignore ([f034daa](https://github.com/Financial-Times/dotcom-tool-kit/commit/f034daa9319a017cced965f857fae9bb1c8d7f63))
* **create:** add suggestions to all required options ([2569e3f](https://github.com/Financial-Times/dotcom-tool-kit/commit/2569e3fdefc193298306844622f6238e74826084))
* **create:** infer Heroku options based on Biz Ops and Heroku API ([8aa02b6](https://github.com/Financial-Times/dotcom-tool-kit/commit/8aa02b6916592abcdfbf3afa8c6c52e43dff83c5))
* **create:** infer some prompts by Biz Ops data ([cf08228](https://github.com/Financial-Times/dotcom-tool-kit/commit/cf0822832d013a3cad81ec6e4fba4481f7f6d7bf))
* **create:** infer the rest of the Heroku options from Biz Ops data ([e3c626e](https://github.com/Financial-Times/dotcom-tool-kit/commit/e3c626ebfda662845d72c7130d197414fa922a91))
* **create:** infer which plugins to install based on package.json ([0b3ffe3](https://github.com/Financial-Times/dotcom-tool-kit/commit/0b3ffe3b8e10b440e5ddab35b5916b90fe1df163))

### Bug Fixes

* **create:** default all confirmation prompts to the happy path ([8dca215](https://github.com/Financial-Times/dotcom-tool-kit/commit/8dca2157ed42a39e36fb862641a7c6758c64db71))
* **create:** ignore default Makefile target when printing suggestions ([8d92b03](https://github.com/Financial-Times/dotcom-tool-kit/commit/8d92b03c2e0435e6ad3a9c0acdca9cd00be509a5))
* **create:** present option to overwrite ESLint config ([d9bfe5d](https://github.com/Financial-Times/dotcom-tool-kit/commit/d9bfe5d7a1b13f4130ae8b8a8de4a12267e6f8b0))
* **create:** tweak ESLint prompt to be more assertive ([da2fc2e](https://github.com/Financial-Times/dotcom-tool-kit/commit/da2fc2eed07f3a583aacfc1b2d3878ce87162d0f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
  * devDependencies
    * dotcom-tool-kit bumped from ^3.3.10 to ^3.3.11
</details>

<details><summary>@dotcom-tool-kit/cypress: 3.3.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/doppler: 1.0.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/options bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
    * @dotcom-tool-kit/vault bumped from ^3.1.6 to ^3.1.7
</details>

<details><summary>@dotcom-tool-kit/eslint: 3.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 3.1.25</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.11 to ^3.0.12
    * @dotcom-tool-kit/upload-assets-to-s3 bumped from ^3.1.6 to ^3.1.7
    * @dotcom-tool-kit/webpack bumped from ^3.1.6 to ^3.1.7
</details>

<details><summary>@dotcom-tool-kit/heroku: 3.3.15</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/npm bumped from ^3.2.2 to ^3.2.3
    * @dotcom-tool-kit/options bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>jest: 3.3.0</summary>

### Features

* **jest:** set appropriate max workers in CircleCI environment ([abce8f6](https://github.com/Financial-Times/dotcom-tool-kit/commit/abce8f6d05e67bc8c0892878127de6b27e6c9dd4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 4.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 3.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/lint-staged bumped from ^4.1.5 to ^4.1.6
    * @dotcom-tool-kit/options bumped from ^3.1.5 to ^3.1.6
</details>

<details><summary>logger: 3.3.1</summary>

### Bug Fixes

* **logger:** log if a child process was terminated by a signal ([5a4a9af](https://github.com/Financial-Times/dotcom-tool-kit/commit/5a4a9af7cd57b7f9728c8b59b75c57e0967a8aeb))
</details>

<details><summary>@dotcom-tool-kit/mocha: 3.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/n-test: 3.2.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/next-router: 3.3.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
</details>

<details><summary>@dotcom-tool-kit/node: 3.3.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
</details>

<details><summary>@dotcom-tool-kit/nodemon: 3.3.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
</details>

<details><summary>@dotcom-tool-kit/npm: 3.2.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/options: 3.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.5.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/prettier: 3.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/serverless: 2.2.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^1.0.8 to ^1.0.9
    * @dotcom-tool-kit/options bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>types: 3.5.0</summary>

### Features

* **create:** add suggestions to all required options ([2569e3f](https://github.com/Financial-Times/dotcom-tool-kit/commit/2569e3fdefc193298306844622f6238e74826084))
* **create:** infer Heroku options based on Biz Ops and Heroku API ([8aa02b6](https://github.com/Financial-Times/dotcom-tool-kit/commit/8aa02b6916592abcdfbf3afa8c6c52e43dff83c5))
* **create:** infer the rest of the Heroku options from Biz Ops data ([e3c626e](https://github.com/Financial-Times/dotcom-tool-kit/commit/e3c626ebfda662845d72c7130d197414fa922a91))

### Bug Fixes

* **create:** default all confirmation prompts to the happy path ([8dca215](https://github.com/Financial-Times/dotcom-tool-kit/commit/8dca2157ed42a39e36fb862641a7c6758c64db71))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
</details>

<details><summary>@dotcom-tool-kit/typescript: 2.1.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 3.1.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/vault: 3.1.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>@dotcom-tool-kit/webpack: 3.1.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
</details>

<details><summary>dotcom-tool-kit: 3.3.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^3.3.0 to ^3.3.1
    * @dotcom-tool-kit/options bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/types bumped from ^3.4.1 to ^3.5.0
  * devDependencies
    * @dotcom-tool-kit/babel bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.11 to ^3.0.12
    * @dotcom-tool-kit/circleci bumped from ^5.3.8 to ^5.3.9
    * @dotcom-tool-kit/circleci-deploy bumped from ^3.2.8 to ^3.2.9
    * @dotcom-tool-kit/eslint bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/frontend-app bumped from ^3.1.24 to ^3.1.25
    * @dotcom-tool-kit/heroku bumped from ^3.3.14 to ^3.3.15
    * @dotcom-tool-kit/mocha bumped from ^3.1.5 to ^3.1.6
    * @dotcom-tool-kit/n-test bumped from ^3.2.7 to ^3.2.8
    * @dotcom-tool-kit/npm bumped from ^3.2.2 to ^3.2.3
    * @dotcom-tool-kit/webpack bumped from ^3.1.6 to ^3.1.7
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by ivomurrell — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v3.3.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v3.4.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/doppler-v1.0.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v3.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v3.5.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v3.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v3.1.24 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-heroku-app-v3.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-serverless-app-v3.0.13 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v5.3.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-deploy-v3.2.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v3.1.24 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v5.2.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/component-v4.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/cypress-v3.3.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v3.1.25 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v3.3.15 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v3.3.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v4.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v3.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v3.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v3.2.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v3.3.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v3.3.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v3.3.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/pa11y-v0.5.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v3.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/serverless-v2.2.13 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/typescript-v2.1.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v3.1.7 :sunflower:

**Pull request merged**
