### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/backend-heroku-app: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/heroku bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/node bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/npm bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>@dotcom-tool-kit/backend-serverless-app: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/node bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/npm bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/serverless bumped from ^3.0.0 to ^3.0.1
</details>

<details><summary>circleci: 7.0.1</summary>

### Bug Fixes

* **circleci:** remove leftover references to deleted waiting-for-approval ([4ed4634](https://github.com/Financial-Times/dotcom-tool-kit/commit/4ed46345c88e5e85ae29472605f29b9ab3383772))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>circleci-deploy: 4.0.1</summary>

### Bug Fixes

* **circleci:** remove leftover references to deleted waiting-for-approval ([4ed4634](https://github.com/Financial-Times/dotcom-tool-kit/commit/4ed46345c88e5e85ae29472605f29b9ab3383772))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^7.0.0 to ^7.0.1
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 6.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^7.0.0 to ^7.0.1
    * @dotcom-tool-kit/npm bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>commitlint: 1.0.0</summary>

### Features

* **commitlint:** add a Commitlint plugin ([c073db5](https://github.com/Financial-Times/dotcom-tool-kit/commit/c073db5c45b8c6f7488f07dd1eaf278d6f8b6db8))
</details>

<details><summary>@dotcom-tool-kit/component: 5.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-npm bumped from ^6.0.0 to ^6.0.1
    * @dotcom-tool-kit/npm bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>@dotcom-tool-kit/config: 1.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/create: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
  * devDependencies
    * dotcom-tool-kit bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>@dotcom-tool-kit/cypress: 5.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/doppler: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/eslint: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>frontend-app: 4.0.1</summary>

### Bug Fixes

* **webpack:** define Webpack task options for commands ([d3b55cd](https://github.com/Financial-Times/dotcom-tool-kit/commit/d3b55cdd3ef499707a808171ac0c253e54791489))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/upload-assets-to-s3 bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/webpack bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>@dotcom-tool-kit/heroku: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
    * @dotcom-tool-kit/npm bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/options bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/husky-npm: 5.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
</details>

<details><summary>@dotcom-tool-kit/jest: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 5.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/husky-npm bumped from ^5.0.0 to ^5.0.1
    * @dotcom-tool-kit/lint-staged bumped from ^5.0.0 to ^5.0.1
    * @dotcom-tool-kit/options bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
</details>

<details><summary>@dotcom-tool-kit/mocha: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/n-test: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/next-router: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/node: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/nodemon: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/npm: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
</details>

<details><summary>@dotcom-tool-kit/options: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/package-json-hook: 5.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/prettier: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.0 to ^5.0.1
</details>

<details><summary>schemas: 1.1.0</summary>

### Features

* **commitlint:** add a Commitlint plugin ([c073db5](https://github.com/Financial-Times/dotcom-tool-kit/commit/c073db5c45b8c6f7488f07dd1eaf278d6f8b6db8))
</details>

<details><summary>@dotcom-tool-kit/serverless: 3.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.0 to ^2.0.1
    * @dotcom-tool-kit/options bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/typescript: 3.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>webpack: 4.0.1</summary>

### Bug Fixes

* **webpack:** define Webpack task options for commands ([d3b55cd](https://github.com/Financial-Times/dotcom-tool-kit/commit/d3b55cdd3ef499707a808171ac0c253e54791489))

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.0.0 to ^1.1.0
</details>

<details><summary>dotcom-tool-kit: 4.0.1</summary>

### Bug Fixes

* **cli:** correctly check for conflicting command tasks ([666a9aa](https://github.com/Financial-Times/dotcom-tool-kit/commit/666a9aa9a7c5b4575ad16b5d15c17205c9fea0fb))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/config bumped from ^1.0.0 to ^1.0.1
    * @dotcom-tool-kit/options bumped from ^4.0.0 to ^4.0.1
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by rowanmanning** [comment]
Oof that's noisy with the @dotcom-tool-kit/schema change 😐

**Comment by ivomurrell** [comment]
> Oof that's noisy with the @dotcom-tool-kit/schema change 😐

At some point we'll look at rearchitecting `schema` so every plugin doesn't need to depend on it 😅

**Review by ivomurrell — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/config-v1.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/doppler-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/schemas-v1.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-heroku-app-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-serverless-app-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v7.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-deploy-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v6.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/commitlint-v1.0.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/component-v5.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/cypress-v5.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/eslint-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/husky-npm-v5.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v5.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/package-json-hook-v5.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/serverless-v3.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/typescript-v3.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v4.0.1 :sunflower:

**Pull request merged**
