### PR TITLE
chore: upgrade sandbox dev dependency versions

### PR DESCRIPTION
**Pull request by andygout**
# Description

I upgraded all the dotcom-tool-kit dependencies in [next-newsletter-signup](https://github.com/Financial-Times/next-newsletter-signup) to the latest available versions (released yesterday: 19 Apr 2023).

My installation process encountered the following:
Screenshot 2023-04-20 at 09 18 38

I pulled down the latest version of this repo and looked for where instances of v2 of `@dotcom-tool-kit/frontend-app` might be coming from, as this seems to be the origin of the conflicting version of `@dotcom-tool-kit/circleci`.

Searching across all files for `@dotcom-tool-kit/frontend-app": "^2` produced two results in the `package-lock.json` - under `"core/sandbox"` and `"@dotcom-tool-kit/sandbox"` respectively, which makes me think that this is where the v2 instance of `@dotcom-tool-kit/frontend-app` is originating.

However, as I finish writing this PR description, I can see that the test on this branch have failed in the CI workflow: https://app.circleci.com/pipelines/github/Financial-Times/dotcom-tool-kit/3391/workflows/864df9f8-f044-4679-9ca7-5e66383daed6/jobs/18845 🤔 I'll take a deeper look 👀 

# Checklist:

- [x] My branch has been rebased onto the latest commit on main (don't merge main into your branch)
- [x] My commit messages are [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), for example: `feat(circleci): add support for nightly workflows`, `fix: set Heroku app name for staging apps too`

### CODE REVIEW

**Comment by jkerr321** [comment]
@andygout this command should definitively install the latest versions for you across the repo: 
```
volta run --npm latest npm query ":root > [name*=dotcom-tool-kit]" | jq '.[] | .name + "@latest"' -r | xargs npm install
```

Is it worth giving that a try?

**Comment by andygout** [comment]
Hmm

```bash
-r | xargs npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@dotcom-tool-kit%2fsandbox - Not found
npm ERR! 404 
npm ERR! 404  '@dotcom-tool-kit/sandbox@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     {path}/.npm/_logs/2023-04-20T09_09_09_626Z-debug-0.log
```

**Comment by andygout** [comment]
I also tried `npm i --force` as the first error message suggested, which even though it felt wrong allowed me to complete installation, but this subsequently resulted in this build failure: https://app.circleci.com/pipelines/github/Financial-Times/next-newsletter-signup/3360/workflows/65c5b7b4-be9f-4b02-a8e6-f82755d6975c/jobs/10637.

**Comment by apaleslimghost** [comment]
closing this as we removed the sandbox from Git in #504

**Pull request closed without merging**
