### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 2.0.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>backend-app: 2.1.0</summary>

### Features

* **backend-app:** add secret-squirrel as dep ([f90c30e](https://github.com/Financial-Times/dotcom-tool-kit/commit/f90c30eb6a1c53cff064ac83d919bf2bd69b5983))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/node bumped from ^2.2.3 to ^2.2.4
    * @dotcom-tool-kit/npm bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/secret-squirrel bumped from ^1.0.9 to ^1.0.10
</details>

<details><summary>circleci: 3.0.1</summary>

### Bug Fixes

* **circle:** remove filter job options from nightly jobs ([1c94b6a](https://github.com/Financial-Times/dotcom-tool-kit/commit/1c94b6afc6c9748e910b8d49474df1b105120db0))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.1 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>circleci-heroku: 2.2.0</summary>

### Features

* **circleci-heroku:** add heroku-provision to Nightly workflow ([63baa6e](https://github.com/Financial-Times/dotcom-tool-kit/commit/63baa6e942ad87ef82d6804d5541bb22f8ac2c94))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^3.0.0 to ^3.0.1
    * @dotcom-tool-kit/heroku bumped from ^2.1.1 to ^2.1.2
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 3.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
    * @dotcom-tool-kit/circleci bumped from ^3.0.0 to ^3.0.1
    * @dotcom-tool-kit/npm bumped from ^2.0.11 to ^2.0.12
</details>

<details><summary>component: 2.1.0</summary>

### Features

* **component:** add secret-squirrel as dep ([15ed469](https://github.com/Financial-Times/dotcom-tool-kit/commit/15ed4692c8cde7ca57887f9ebebb0f1993385180))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-npm bumped from ^3.0.0 to ^3.0.1
    * @dotcom-tool-kit/npm bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/secret-squirrel bumped from ^1.0.9 to ^1.0.10
</details>

<details><summary>create: 2.4.0</summary>

### Features

* **create:** add migration path for scheduled workflows ([2849198](https://github.com/Financial-Times/dotcom-tool-kit/commit/2849198fd78035d23a0f5eda21d57c49c631f983))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
  * devDependencies
    * dotcom-tool-kit bumped from ^2.4.0 to ^2.4.1
</details>

<details><summary>@dotcom-tool-kit/eslint: 2.2.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 2.1.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.13 to ^2.1.0
    * @dotcom-tool-kit/webpack bumped from ^2.1.9 to ^2.1.10
</details>

<details><summary>@dotcom-tool-kit/heroku: 2.1.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/npm bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
    * @dotcom-tool-kit/vault bumped from ^2.0.10 to ^2.0.11
</details>

<details><summary>@dotcom-tool-kit/jest: 2.0.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 3.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/lint-staged bumped from ^3.0.0 to ^3.0.1
    * @dotcom-tool-kit/options bumped from ^2.0.10 to ^2.0.11
</details>

<details><summary>logger: 2.2.0</summary>

### Features

* **logger:** reduce noise created by metadata prefixes ([0321e6b](https://github.com/Financial-Times/dotcom-tool-kit/commit/0321e6b151d6c4ea9b496c2e5211860163da8a2e))
</details>

<details><summary>mocha: 2.2.0</summary>

### Features

* **mocha:** widen mocha dependency range and make peer ([412d7f9](https://github.com/Financial-Times/dotcom-tool-kit/commit/412d7f9001eb47f53f30d6b1f482c0047aab6cc2))

### Bug Fixes

* **mocha:** remove accidentally installed fs package ([01633ef](https://github.com/Financial-Times/dotcom-tool-kit/commit/01633ef7cb81dae339e29a7df3fa7da0d4f9611d))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/n-test: 2.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/next-router: 2.0.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
    * @dotcom-tool-kit/vault bumped from ^2.0.10 to ^2.0.11
</details>

<details><summary>@dotcom-tool-kit/node: 2.2.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
    * @dotcom-tool-kit/vault bumped from ^2.0.10 to ^2.0.11
</details>

<details><summary>@dotcom-tool-kit/nodemon: 2.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
    * @dotcom-tool-kit/vault bumped from ^2.0.10 to ^2.0.11
</details>

<details><summary>@dotcom-tool-kit/npm: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/options: 2.0.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.3.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.1.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/secret-squirrel: 1.0.10</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/types: 2.7.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.1 to ^2.2.0
</details>

<details><summary>upload-assets-to-s3: 2.0.12</summary>

### Bug Fixes

* **upload-assets-to-s3:** only upload files ([e4d17d9](https://github.com/Financial-Times/dotcom-tool-kit/commit/e4d17d99b4d2c0245064cd2352018f231395df00))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/vault: 2.0.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.10 to ^2.0.11
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>@dotcom-tool-kit/webpack: 2.1.10</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
</details>

<details><summary>dotcom-tool-kit: 2.4.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.2 to ^2.2.0
    * @dotcom-tool-kit/options bumped from ^2.0.10 to ^2.0.11
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.7.1
  * devDependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.13 to ^2.1.0
    * @dotcom-tool-kit/heroku bumped from ^2.1.1 to ^2.1.2
    * @dotcom-tool-kit/webpack bumped from ^2.1.9 to ^2.1.10
    * @dotcom-tool-kit/babel bumped from ^2.0.10 to ^2.0.11
    * @dotcom-tool-kit/circleci bumped from ^3.0.0 to ^3.0.1
    * @dotcom-tool-kit/npm bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/frontend-app bumped from ^2.1.11 to ^2.1.12
    * @dotcom-tool-kit/eslint bumped from ^2.2.3 to ^2.2.4
    * @dotcom-tool-kit/mocha bumped from ^2.1.7 to ^2.2.0
    * @dotcom-tool-kit/n-test bumped from ^2.1.5 to ^2.1.6
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by joelcarr** [comment]
Looks good to me! Shall we do a release first (merging #322) then merge this in?

**Review by joelcarr — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.4.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.4.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/logger-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v2.7.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/vault-v2.0.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v2.0.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v3.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/component-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/eslint-v2.2.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v2.1.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v2.0.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v3.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v2.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v2.0.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v2.2.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v2.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/pa11y-v0.3.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/secret-squirrel-v1.0.10 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v2.0.12 :sunflower:

**Pull request merged**
