### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 2.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/backend-app: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/npm bumped from ^2.0.4 to ^2.0.5
    * @dotcom-tool-kit/node bumped from ^2.1.0 to ^2.1.1
</details>

<details><summary>@dotcom-tool-kit/circleci: 2.1.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^2.1.1 to ^2.1.2
    * @dotcom-tool-kit/heroku bumped from ^2.0.4 to ^2.0.5
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 2.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
    * @dotcom-tool-kit/circleci bumped from ^2.1.1 to ^2.1.2
    * @dotcom-tool-kit/npm bumped from ^2.0.4 to ^2.0.5
</details>

<details><summary>create: 2.1.0</summary>

### Features

* **core:** gather errors when loading config and throw all together ([f57a4b4](https://github.com/Financial-Times/dotcom-tool-kit/commit/f57a4b439d1bc80471f5717ed40bdea3156a7a15))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
    * dotcom-tool-kit bumped from ^2.2.3 to ^2.3.0
</details>

<details><summary>@dotcom-tool-kit/eslint: 2.1.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 2.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/webpack bumped from ^2.1.2 to ^2.1.3
</details>

<details><summary>heroku: 2.0.5</summary>

### Bug Fixes

* filter appFormation array by type ([8ea0362](https://github.com/Financial-Times/dotcom-tool-kit/commit/8ea0362f1fe979e7d3505621186257e8d9bf407c))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/npm bumped from ^2.0.4 to ^2.0.5
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
    * @dotcom-tool-kit/vault bumped from ^2.0.3 to ^2.0.4
</details>

<details><summary>@dotcom-tool-kit/jest: 2.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 2.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/lint-staged bumped from ^2.1.3 to ^2.1.4
    * @dotcom-tool-kit/options bumped from ^2.0.3 to ^2.0.4
</details>

<details><summary>logger: 2.1.0</summary>

### Features

* add style for logging code snippets ([de80bfd](https://github.com/Financial-Times/dotcom-tool-kit/commit/de80bfdb1458f44db2fc1c47174600b34deb98d3))
* add style for logging code snippets ([13823bc](https://github.com/Financial-Times/dotcom-tool-kit/commit/13823bc767ef7235e122750f9c59b1501578e617))
</details>

<details><summary>@dotcom-tool-kit/mocha: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/n-test: 2.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/next-router: 2.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
    * @dotcom-tool-kit/vault bumped from ^2.0.3 to ^2.0.4
</details>

<details><summary>@dotcom-tool-kit/node: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
    * @dotcom-tool-kit/vault bumped from ^2.0.3 to ^2.0.4
</details>

<details><summary>@dotcom-tool-kit/nodemon: 2.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
    * @dotcom-tool-kit/vault bumped from ^2.0.3 to ^2.0.4
</details>

<details><summary>@dotcom-tool-kit/npm: 2.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/options: 2.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.2.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/secret-squirrel: 1.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>types: 2.4.0</summary>

### Features

* add validation errors to compatibility test in types package ([ac118b3](https://github.com/Financial-Times/dotcom-tool-kit/commit/ac118b37bdbb30e062a2d559cc37dc36af4bcb73))
* add validation errors to compatibility test in types package ([5228fab](https://github.com/Financial-Times/dotcom-tool-kit/commit/5228fab26ccee26bd786480bf280f6b91965679f))
* loosen task and hook instance checks ([ac118b3](https://github.com/Financial-Times/dotcom-tool-kit/commit/ac118b37bdbb30e062a2d559cc37dc36af4bcb73))
* loosen task and hook instance checks ([d79b7cf](https://github.com/Financial-Times/dotcom-tool-kit/commit/d79b7cfb5aed68be8b451dd2961f1abe3624c7b9))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 2.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/vault: 2.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.3 to ^2.0.4
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>@dotcom-tool-kit/webpack: 2.1.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
</details>

<details><summary>dotcom-tool-kit: 2.3.0</summary>

### Features

* add style for logging code snippets ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))
* add validation errors to compatibility test in types package ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))
* **cli:** include error message when plugin cannot be imported ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))
* **core:** gather errors when loading config and throw all together ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))
* **core:** group multiple validation errors in a nested list ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))
* **core:** improve error messages when plugins are invalid ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))
* loosen task and hook instance checks ([82abb8e](https://github.com/Financial-Times/dotcom-tool-kit/commit/82abb8e44372d0c3afc36b13dd62d888de11cb92))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/options bumped from ^2.0.3 to ^2.0.4
    * @dotcom-tool-kit/types bumped from ^2.3.0 to ^2.4.0
  * devDependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/heroku bumped from ^2.0.4 to ^2.0.5
    * @dotcom-tool-kit/webpack bumped from ^2.1.2 to ^2.1.3
    * @dotcom-tool-kit/babel bumped from ^2.0.3 to ^2.0.4
    * @dotcom-tool-kit/circleci bumped from ^2.1.1 to ^2.1.2
    * @dotcom-tool-kit/npm bumped from ^2.0.4 to ^2.0.5
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/frontend-app bumped from ^2.1.3 to ^2.1.4
    * @dotcom-tool-kit/eslint bumped from ^2.1.2 to ^2.1.3
    * @dotcom-tool-kit/mocha bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/n-test bumped from ^2.0.4 to ^2.0.5
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by serena97 — CHANGES_REQUESTED** [review]
core/cli and core/create should have minor version bumped instead of patch version according to https://github.com/Financial-Times/dotcom-tool-kit/pull/245/files#diff-bcb367d845abe8b9d0506e036742e358f9d2c036c80110dc28bd581dc63bc92e , this needs to be investigated and fixed

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.3.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/logger-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v2.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v2.4.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/vault-v2.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v2.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v2.1.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v2.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/eslint-v2.1.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v2.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v2.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v2.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v2.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v2.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v2.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v2.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/pa11y-v0.2.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v2.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/secret-squirrel-v1.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v2.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v2.1.3 :sunflower:

**Pull request merged**
