### PR TITLE
backstage: disallow chore commits, introduce backstage commits

### PR DESCRIPTION
**Pull request by apaleslimghost**
CPP-2112

### CODE REVIEW

**Review by ivomurrell — APPROVED** [review]
thank you!! i hate `chore`!!

**Review by joelcarr — COMMENTED** [review]
**chore:** We should add documentation to mention these are the prefixes we support.

**Review by cerdfied — APPROVED** [review]

**Comment by cerdfied** [comment]
> ~**chore:**~ **backstage:** We should add documentation to mention these are the prefixes we support.

agreed, we should probably update [here](https://github.com/Financial-Times/cp-content-pipeline/blob/main/CONTRIBUTING.md#commit-type-prefixes)

**Comment by cerdfied** [comment]
> ~**chore:**~ **backstage:** We should add documentation to mention these are the prefixes we support.

agreed, we should probably add something [here](https://github.com/Financial-Times/dotcom-tool-kit?tab=readme-ov-file#contributing) like in [content-pipeline](https://github.com/Financial-Times/cp-content-pipeline/blob/main/CONTRIBUTING.md#commit-type-prefixes)

**Pull request merged**
