### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/backend-app: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.0 to ^2.0.1
    * @dotcom-tool-kit/npm bumped from ^2.0.0 to ^2.0.1
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/heroku bumped from ^2.0.0 to ^2.0.1
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^2.0.0 to ^2.0.1
</details>

<details><summary>@dotcom-tool-kit/create: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * dotcom-tool-kit bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>frontend-app: 2.0.1</summary>

### Bug Fixes

* **frontend-app:** don't include Babel in config ([fefdc81](https://github.com/Financial-Times/dotcom-tool-kit/commit/fefdc81841198723532b8d9cc5a0f7ff763aa0a3))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.0 to ^2.0.1
</details>

<details><summary>heroku: 2.0.1</summary>

### Bug Fixes

* **heroku:** set NODE_ENV to 'branch' for review apps ([05c62dd](https://github.com/Financial-Times/dotcom-tool-kit/commit/05c62dd9415f20e83728f1cbf0051f9802d74044))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^2.0.0 to ^2.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>husky-npm: 2.1.0</summary>

### Features

* move HuskyHook into husky-npm ([c9f35f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/c9f35f823e1ef57bf30f5c26d8a8907481136909))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>lint-staged: 2.1.0</summary>

### Features

* remove hook package and move PackageJsonHelper into package-json-hook ([b22e5d3](https://github.com/Financial-Times/dotcom-tool-kit/commit/b22e5d36ebfdc50cfa57586489a1107e35631bcc))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/husky-npm bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/lint-staged bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>npm: 2.0.1</summary>

### Bug Fixes

* remove references to deleted plugin ([f7dbd47](https://github.com/Financial-Times/dotcom-tool-kit/commit/f7dbd471ecb8f022d684e8e31a4584e2da636c87))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>package-json-hook: 2.1.0</summary>

### Features

* remove hook package and move PackageJsonHelper into package-json-hook ([b22e5d3](https://github.com/Financial-Times/dotcom-tool-kit/commit/b22e5d36ebfdc50cfa57586489a1107e35631bcc))
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^2.0.0 to ^2.1.0
</details>

<details><summary>dotcom-tool-kit: 2.1.0</summary>

### Features

* remove hook package and move PackageJsonHelper into package-json-hook ([b22e5d3](https://github.com/Financial-Times/dotcom-tool-kit/commit/b22e5d36ebfdc50cfa57586489a1107e35631bcc))

### Bug Fixes

* ensure we correctly consider conflicts from cousin plugins ([0a38996](https://github.com/Financial-Times/dotcom-tool-kit/commit/0a389967f6b1f2181e2d76935392c4b1a658c27b))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by apaleslimghost — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/package-json-hook-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v2.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/husky-npm-v2.1.0 :sunflower:

**Pull request merged**
