### PR TITLE
Improve hookFook error message

### PR DESCRIPTION
**Pull request by ivomurrell**
Based on https://financialtimes.slack.com/archives/C02TRE2V2Q1/p1655469494095279

### CODE REVIEW

**Review by GlynnPhillips — APPROVED** [review]
Nice, thanks Ivo

**Comment by joelcarr** [comment]
@ivomurrell is this still relevant?

**Comment by ivomurrell** [comment]
> @ivomurrell is this still relevant?

Yes! I've rebased the changes onto main so they should be ready to review.

**Review by jkerr321 — APPROVED** [review]

**Comment by apaleslimghost** [comment]
"hookFook" lol

**Pull request merged**
