### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/backend-app: 3.1.20</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.7 to ^3.0.8
</details>

<details><summary>@dotcom-tool-kit/backend-heroku-app: 3.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/heroku bumped from ^3.3.10 to ^3.3.11
    * @dotcom-tool-kit/npm bumped from ^3.2.1 to ^3.2.2
</details>

<details><summary>@dotcom-tool-kit/backend-serverless-app: 3.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^3.2.1 to ^3.2.2
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 3.1.20</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/heroku bumped from ^3.3.10 to ^3.3.11
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 5.2.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^3.2.1 to ^3.2.2
</details>

<details><summary>@dotcom-tool-kit/component: 4.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-npm bumped from ^5.2.10 to ^5.2.11
    * @dotcom-tool-kit/npm bumped from ^3.2.1 to ^3.2.2
</details>

<details><summary>@dotcom-tool-kit/create: 3.2.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * dotcom-tool-kit bumped from ^3.3.6 to ^3.3.7
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 3.1.21</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.7 to ^3.0.8
</details>

<details><summary>@dotcom-tool-kit/heroku: 3.3.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^3.2.1 to ^3.2.2
</details>

<details><summary>npm: 3.2.2</summary>

### Bug Fixes

* **npm:** revert "Merge pull request [#501](https://github.com/Financial-Times/dotcom-tool-kit/issues/501) from Financial-Times/CPP-1722-fix-npm-publish-task" ([d4d6e1b](https://github.com/Financial-Times/dotcom-tool-kit/commit/d4d6e1bdc28cd19cd39e9cda035ee96ef025de9b))
* **npm:** revert "Merge pull request [#503](https://github.com/Financial-Times/dotcom-tool-kit/issues/503) from Financial-Times/fix-npm-publish-log-task" ([0a78f1e](https://github.com/Financial-Times/dotcom-tool-kit/commit/0a78f1e2d6bd793d56f56f2feb9a8b619b55913f))
* **npm:** revert "Merge pull request [#505](https://github.com/Financial-Times/dotcom-tool-kit/issues/505) from Financial-Times/fix-npm-no-git-version" ([7bafd97](https://github.com/Financial-Times/dotcom-tool-kit/commit/7bafd97829f9695b5c0b636e90a359c1555ef888))
* **npm:** write package version to packagejson before bundling ([864d699](https://github.com/Financial-Times/dotcom-tool-kit/commit/864d6990d1e9431b223a5c6108a06d5d1933f5f2))
</details>

<details><summary>dotcom-tool-kit: 3.3.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.7 to ^3.0.8
    * @dotcom-tool-kit/frontend-app bumped from ^3.1.20 to ^3.1.21
    * @dotcom-tool-kit/heroku bumped from ^3.3.10 to ^3.3.11
    * @dotcom-tool-kit/npm bumped from ^3.2.1 to ^3.2.2
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by joelcarr — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v3.3.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v3.2.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v3.1.20 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-heroku-app-v3.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-serverless-app-v3.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v3.1.20 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v5.2.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/component-v4.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v3.1.21 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v3.3.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v3.2.2 :sunflower:

**Pull request merged**
