### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/backend-app: 2.0.10</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.9 to ^2.0.10
    * @dotcom-tool-kit/npm bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/node bumped from ^2.1.3 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/circleci: 2.1.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 2.0.10</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^2.1.4 to ^2.1.5
    * @dotcom-tool-kit/heroku bumped from ^2.0.8 to ^2.0.9
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
    * @dotcom-tool-kit/circleci bumped from ^2.1.4 to ^2.1.5
    * @dotcom-tool-kit/npm bumped from ^2.0.7 to ^2.0.8
</details>

<details><summary>@dotcom-tool-kit/create: 2.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
    * dotcom-tool-kit bumped from ^2.3.3 to ^2.3.4
</details>

<details><summary>eslint: 2.2.0</summary>

### Features

* deprecate config in favour for options in eslint ([831324a](https://github.com/Financial-Times/dotcom-tool-kit/commit/831324a40df17ca947fc000f51e011a2e79a4f91))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 2.1.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.9 to ^2.0.10
    * @dotcom-tool-kit/webpack bumped from ^2.1.5 to ^2.1.6
</details>

<details><summary>@dotcom-tool-kit/heroku: 2.0.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
    * @dotcom-tool-kit/vault bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>@dotcom-tool-kit/jest: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 2.1.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/lint-staged bumped from ^2.1.6 to ^2.1.7
    * @dotcom-tool-kit/options bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>@dotcom-tool-kit/mocha: 2.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/n-test: 2.1.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/next-router: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
    * @dotcom-tool-kit/vault bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>node: 2.2.0</summary>

### Features

* **node:** allow specifying ports ([20f797a](https://github.com/Financial-Times/dotcom-tool-kit/commit/20f797a9d547863c2e5fd3a40948ec62e575cbf8))
* **node:** make vault optional ([cd12619](https://github.com/Financial-Times/dotcom-tool-kit/commit/cd12619346cfc92d67325c7ec4065a228e414f8c))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
    * @dotcom-tool-kit/vault bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>nodemon: 2.1.0</summary>

### Features

* **nodemon:** allow specifying preferred ports ([0aab812](https://github.com/Financial-Times/dotcom-tool-kit/commit/0aab812dfab4eb778c5007eb6ddb2db99a9cc3b2))
* **nodemon:** make vault optional ([9d28d95](https://github.com/Financial-Times/dotcom-tool-kit/commit/9d28d95b7b76fea14741f484d08abc19dc522911))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
    * @dotcom-tool-kit/vault bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>@dotcom-tool-kit/npm: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/options: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.3.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/secret-squirrel: 1.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>types: 2.6.0</summary>

### Features

* deprecate config in favour for options in eslint ([831324a](https://github.com/Financial-Times/dotcom-tool-kit/commit/831324a40df17ca947fc000f51e011a2e79a4f91))
* **node:** allow specifying ports ([20f797a](https://github.com/Financial-Times/dotcom-tool-kit/commit/20f797a9d547863c2e5fd3a40948ec62e575cbf8))
* **node:** make vault optional ([cd12619](https://github.com/Financial-Times/dotcom-tool-kit/commit/cd12619346cfc92d67325c7ec4065a228e414f8c))
* **nodemon:** allow specifying preferred ports ([0aab812](https://github.com/Financial-Times/dotcom-tool-kit/commit/0aab812dfab4eb778c5007eb6ddb2db99a9cc3b2))
* **nodemon:** make vault optional ([9d28d95](https://github.com/Financial-Times/dotcom-tool-kit/commit/9d28d95b7b76fea14741f484d08abc19dc522911))
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/vault: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>@dotcom-tool-kit/webpack: 2.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
</details>

<details><summary>dotcom-tool-kit: 2.3.4</summary>

### Bug Fixes

* **cli:** avoid infinite loop when custom plugin doesn't have config ([3f4dae2](https://github.com/Financial-Times/dotcom-tool-kit/commit/3f4dae21d36702f581b42e65366960df91332a69))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/types bumped from ^2.5.1 to ^2.6.0
  * devDependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.9 to ^2.0.10
    * @dotcom-tool-kit/heroku bumped from ^2.0.8 to ^2.0.9
    * @dotcom-tool-kit/webpack bumped from ^2.1.5 to ^2.1.6
    * @dotcom-tool-kit/babel bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/circleci bumped from ^2.1.4 to ^2.1.5
    * @dotcom-tool-kit/npm bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.9 to ^2.0.10
    * @dotcom-tool-kit/frontend-app bumped from ^2.1.7 to ^2.1.8
    * @dotcom-tool-kit/eslint bumped from ^2.1.5 to ^2.2.0
    * @dotcom-tool-kit/mocha bumped from ^2.1.3 to ^2.1.4
    * @dotcom-tool-kit/n-test bumped from ^2.1.1 to ^2.1.2
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by serena97 — APPROVED** [review]

**Review by serena97 — CHANGES_REQUESTED** [review]
The changes look as expected, however let's wait till https://github.com/Financial-Times/dotcom-tool-kit/pull/292/files is merged in before merging this release pls PR as it has changes to @dotcom-tool-kit/types too

**Review by serena97 — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.3.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v2.6.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/vault-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.0.10 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v2.1.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.0.10 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/eslint-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v2.1.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v2.0.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v2.1.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v2.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v2.1.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/pa11y-v0.3.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/secret-squirrel-v1.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v2.1.6 :sunflower:

**Pull request merged**
