### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>babel: 4.1.0</summary>

### Features

* use cwd from task run context in remaining tasks ([c070cc2](https://github.com/Financial-Times/dotcom-tool-kit/commit/c070cc226b4633939fff349894a4a1a9d1987eef))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>@dotcom-tool-kit/backend-heroku-app: 4.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^4.0.2 to ^4.0.3
    * @dotcom-tool-kit/heroku bumped from ^4.0.2 to ^4.0.3
    * @dotcom-tool-kit/node bumped from ^4.0.2 to ^4.1.0
    * @dotcom-tool-kit/npm bumped from ^4.0.2 to ^4.1.0
</details>

<details><summary>@dotcom-tool-kit/backend-serverless-app: 4.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-deploy bumped from ^4.0.2 to ^4.0.3
    * @dotcom-tool-kit/node bumped from ^4.0.2 to ^4.1.0
    * @dotcom-tool-kit/npm bumped from ^4.0.2 to ^4.1.0
    * @dotcom-tool-kit/serverless bumped from ^3.0.2 to ^3.1.0
</details>

<details><summary>base: 1.1.0</summary>

### Features

* pass config into taskruncontext ([435ffbc](https://github.com/Financial-Times/dotcom-tool-kit/commit/435ffbc74a81bdd159d4ea01943c6614ed1d3471))
* pass current command into task run context ([e4cf21c](https://github.com/Financial-Times/dotcom-tool-kit/commit/e4cf21c8c4e502b02918736b8b127097dba27572))
* pass task cwd through via TaskRunContext ([b12fe30](https://github.com/Financial-Times/dotcom-tool-kit/commit/b12fe30916e99e157e131a99fca6c59960b89f3a))

### Bug Fixes

* freeze the config before passing it into tasks ([a0283b9](https://github.com/Financial-Times/dotcom-tool-kit/commit/a0283b9b5a48314a26ce04ce4c176ab5f4aacc07))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/validated bumped from ^1.0.0 to ^1.0.1
  * devDependencies
    * @dotcom-tool-kit/config bumped from ^1.0.2 to ^1.0.3
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>circleci: 7.1.0</summary>

### Features

* **circleci:** allow plugins to only specify a subset of hook options ([c39850a](https://github.com/Financial-Times/dotcom-tool-kit/commit/c39850a4df4884bd3141288b3c2bf583c276a65c))
* **circleci:** allow workflow job options to be merged ([e33e579](https://github.com/Financial-Times/dotcom-tool-kit/commit/e33e579fe33a48ea1485a56f92da39e9818d56dc))

### Bug Fixes

* add cypressImage to circleci schema ([f09078e](https://github.com/Financial-Times/dotcom-tool-kit/commit/f09078e1b70ad8f6f4281ac317c99a4a078503e8))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>@dotcom-tool-kit/circleci-deploy: 4.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^7.0.2 to ^7.1.0
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 6.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^7.0.2 to ^7.1.0
    * @dotcom-tool-kit/npm bumped from ^4.0.2 to ^4.1.0
</details>

<details><summary>commitlint: 1.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>@dotcom-tool-kit/component: 5.0.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-npm bumped from ^6.0.3 to ^6.0.4
    * @dotcom-tool-kit/npm bumped from ^4.0.2 to ^4.1.0
</details>

<details><summary>@dotcom-tool-kit/config: 1.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
    * @dotcom-tool-kit/validated bumped from ^1.0.0 to ^1.0.1
</details>

<details><summary>create: 4.1.0</summary>

### Features

* add a root option to loadConfig instead of using process.cwd() ([d3f1560](https://github.com/Financial-Times/dotcom-tool-kit/commit/d3f1560a0378e2e21bcbca134e6f9ebf76af068f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
  * devDependencies
    * dotcom-tool-kit bumped from ^4.0.6 to ^4.1.0
</details>

<details><summary>cypress: 5.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>@dotcom-tool-kit/doppler: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>error: 4.0.1</summary>

### Bug Fixes

* add a descriptive name property to ToolKitError ([a68e3fd](https://github.com/Financial-Times/dotcom-tool-kit/commit/a68e3fdf197862e71cf12048933ba1f0cc692161))
</details>

<details><summary>eslint: 4.1.0</summary>

### Features

* use cwd from task run context in remaining tasks ([c070cc2](https://github.com/Financial-Times/dotcom-tool-kit/commit/c070cc226b4633939fff349894a4a1a9d1987eef))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 4.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^4.0.2 to ^4.0.3
    * @dotcom-tool-kit/upload-assets-to-s3 bumped from ^4.0.2 to ^4.1.0
    * @dotcom-tool-kit/webpack bumped from ^4.0.2 to ^4.1.0
</details>

<details><summary>@dotcom-tool-kit/heroku: 4.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/npm bumped from ^4.0.2 to ^4.1.0
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>@dotcom-tool-kit/husky-npm: 5.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
</details>

<details><summary>jest: 4.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>lint-staged: 5.1.0</summary>

### Features

* use cwd from task run context in remaining tasks ([c070cc2](https://github.com/Financial-Times/dotcom-tool-kit/commit/c070cc226b4633939fff349894a4a1a9d1987eef))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 4.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/husky-npm bumped from ^5.0.2 to ^5.0.3
    * @dotcom-tool-kit/lint-staged bumped from ^5.0.2 to ^5.1.0
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
</details>

<details><summary>@dotcom-tool-kit/logger: 4.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>mocha: 4.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>n-test: 4.1.0</summary>

### Features

* use cwd from task run context in remaining tasks ([c070cc2](https://github.com/Financial-Times/dotcom-tool-kit/commit/c070cc226b4633939fff349894a4a1a9d1987eef))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>next-router: 4.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>node: 4.1.0</summary>

### Features

* add support for `node --watch` ([838f206](https://github.com/Financial-Times/dotcom-tool-kit/commit/838f20624a3cbbb944d8077dde556d1b5c0ea784))
* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>nodemon: 4.0.3</summary>

### Bug Fixes

* pass doppler options through in nodemon task ([6cbaac2](https://github.com/Financial-Times/dotcom-tool-kit/commit/6cbaac2caef0f4f255d11c87eda541b111e21712))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>npm: 4.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
</details>

<details><summary>@dotcom-tool-kit/package-json-hook: 5.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>prettier: 4.1.0</summary>

### Features

* use cwd from task run context in remaining tasks ([c070cc2](https://github.com/Financial-Times/dotcom-tool-kit/commit/c070cc226b4633939fff349894a4a1a9d1987eef))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/package-json-hook bumped from ^5.0.2 to ^5.0.3
</details>

<details><summary>schemas: 1.2.0</summary>

### Features

* add support for `node --watch` ([838f206](https://github.com/Financial-Times/dotcom-tool-kit/commit/838f20624a3cbbb944d8077dde556d1b5c0ea784))
* **circleci:** allow plugins to only specify a subset of hook options ([c39850a](https://github.com/Financial-Times/dotcom-tool-kit/commit/c39850a4df4884bd3141288b3c2bf583c276a65c))
* **schemas:** add validation warnings for plugin options that moved to task options ([f9fcb35](https://github.com/Financial-Times/dotcom-tool-kit/commit/f9fcb357bb68d201a39af3d30480804995f44cbb))

### Bug Fixes

* add cypressImage to circleci schema ([f09078e](https://github.com/Financial-Times/dotcom-tool-kit/commit/f09078e1b70ad8f6f4281ac317c99a4a078503e8))
* **schema:** correct suggested task name for eslint options ([b5a3edf](https://github.com/Financial-Times/dotcom-tool-kit/commit/b5a3edf540397f46fe9f96a5e472aa5c75b4f787))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>serverless: 3.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/doppler bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>typescript: 3.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>upload-assets-to-s3: 4.1.0</summary>

### Features

* use cwd from task run context in remaining tasks ([c070cc2](https://github.com/Financial-Times/dotcom-tool-kit/commit/c070cc226b4633939fff349894a4a1a9d1987eef))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>@dotcom-tool-kit/validated: 1.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
</details>

<details><summary>webpack: 4.1.0</summary>

### Features

* run task child processes in the cwd from the task run context ([14d52f8](https://github.com/Financial-Times/dotcom-tool-kit/commit/14d52f81f874a37c12bab3a6fbfddde5ff8d72e7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
  * devDependencies
    * @dotcom-tool-kit/schemas bumped from ^1.1.1 to ^1.2.0
</details>

<details><summary>dotcom-tool-kit: 4.1.0</summary>

### Features

* add a consistent error formatter that can handle AggregateErrors and use it in the cli entrypoint ([ccc2adc](https://github.com/Financial-Times/dotcom-tool-kit/commit/ccc2adcbdb123312d24de6a6beca0bd23010428f))
* add a root option to loadConfig instead of using process.cwd() ([d3f1560](https://github.com/Financial-Times/dotcom-tool-kit/commit/d3f1560a0378e2e21bcbca134e6f9ebf76af068f))
* pass config into taskruncontext ([435ffbc](https://github.com/Financial-Times/dotcom-tool-kit/commit/435ffbc74a81bdd159d4ea01943c6614ed1d3471))
* pass current command into task run context ([e4cf21c](https://github.com/Financial-Times/dotcom-tool-kit/commit/e4cf21c8c4e502b02918736b8b127097dba27572))
* pass task cwd through via TaskRunContext ([b12fe30](https://github.com/Financial-Times/dotcom-tool-kit/commit/b12fe30916e99e157e131a99fca6c59960b89f3a))
* throw an error with a more helpful message from resolveRoot ([6cfaa51](https://github.com/Financial-Times/dotcom-tool-kit/commit/6cfaa51f6b0bf1b0b85c092a69818891aa3f160d))
* use an AggregateError for task errors ([c49d3b3](https://github.com/Financial-Times/dotcom-tool-kit/commit/c49d3b3f714ac517855804535a492ce5e2aa8e94))

### Bug Fixes

* be defensive when getting plugin options for tasks ([55ad81a](https://github.com/Financial-Times/dotcom-tool-kit/commit/55ad81a05bd724aa473f398ba1ba9f14ec354d30))
* better formatting for option validation message ([53e2004](https://github.com/Financial-Times/dotcom-tool-kit/commit/53e20041e4f7bf14005e8ca3ce75d46b3d6a638f))
* correct logic for shouldDisableNativeFetch ([224523b](https://github.com/Financial-Times/dotcom-tool-kit/commit/224523b2f3199daad02bb7a66e09f880432a10c6))
* don't append --no-experimental-fetch multiple times ([edf6443](https://github.com/Financial-Times/dotcom-tool-kit/commit/edf6443e2a07f07c325a3120ded600848d770fda))
* freeze the config before passing it into tasks ([a0283b9](https://github.com/Financial-Times/dotcom-tool-kit/commit/a0283b9b5a48314a26ce04ce4c176ab5f4aacc07))
* friendlier and more readable option validation messages ([2dd4b8c](https://github.com/Financial-Times/dotcom-tool-kit/commit/2dd4b8c71624fbbc2260d816c3c0258602d8eb92))
* get plugin options from the plugin that the hook is from not the plugin installing it ([22ad085](https://github.com/Financial-Times/dotcom-tool-kit/commit/22ad0855daa8abc5d29341cb1fb85fba1e8db07f))
* log an extra newline after error details ([23ea7e4](https://github.com/Financial-Times/dotcom-tool-kit/commit/23ea7e4655116ca0187f1f2906b49080378d7fda))
* more consistent validation messages for moved plugin options ([f70662b](https://github.com/Financial-Times/dotcom-tool-kit/commit/f70662b8cdf5f47a11a9d93f96b5e4efb2dfdf61))
* preserve relative paths in resolveRoot to fix custom plugin loading ([8876631](https://github.com/Financial-Times/dotcom-tool-kit/commit/887663109ac9b0cfb4c39fb038ac111806d0208d))
* resolve a plugin's .toolkitrc.yml ([f1458d8](https://github.com/Financial-Times/dotcom-tool-kit/commit/f1458d8f4116eb6e89bd6322a6513e6368eb7205))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/base bumped from ^1.0.0 to ^1.1.0
    * @dotcom-tool-kit/config bumped from ^1.0.2 to ^1.0.3
    * @dotcom-tool-kit/error bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/logger bumped from ^4.0.0 to ^4.0.1
    * @dotcom-tool-kit/validated bumped from ^1.0.0 to ^1.0.1
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by apaleslimghost — CHANGES_REQUESTED** [review]
despite adding a bunch of tests and all my cajoling @ivomurrell to approve it, there is a bug in #714 that means it can't load custom plugins 😕

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/config-v1.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/error-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/logger-v4.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/schemas-v1.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/validated-v1.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v4.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-deploy-v4.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v6.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/commitlint-v1.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/component-v5.0.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v4.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v4.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/husky-npm-v5.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v4.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v4.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v4.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v4.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v4.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/package-json-hook-v5.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v4.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/serverless-v3.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/typescript-v3.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v4.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v4.1.0 :sunflower:

**Pull request merged**
