### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/backend-app: 3.1.17</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.4 to ^3.0.5
</details>

<details><summary>@dotcom-tool-kit/backend-heroku-app: 3.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/heroku bumped from ^3.3.7 to ^3.3.8
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 3.1.17</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/heroku bumped from ^3.3.7 to ^3.3.8
</details>

<details><summary>@dotcom-tool-kit/create: 3.2.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * dotcom-tool-kit bumped from ^3.3.3 to ^3.3.4
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 3.1.18</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.4 to ^3.0.5
</details>

<details><summary>heroku: 3.3.8</summary>

### Bug Fixes

* **heroku:** only log config var sync if not migrated to Doppler ([6f3cddf](https://github.com/Financial-Times/dotcom-tool-kit/commit/6f3cddfb15f1c2216352f4dedb950ea72ba37944))
</details>

<details><summary>dotcom-tool-kit: 3.3.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * devDependencies
    * @dotcom-tool-kit/backend-heroku-app bumped from ^3.0.4 to ^3.0.5
    * @dotcom-tool-kit/frontend-app bumped from ^3.1.17 to ^3.1.18
    * @dotcom-tool-kit/heroku bumped from ^3.3.7 to ^3.3.8
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by ivomurrell — APPROVED** [review]

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v3.3.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v3.2.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v3.1.17 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-heroku-app-v3.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v3.1.17 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v3.1.18 :sunflower:

**Pull request merged**
