### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/backend-app: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/npm bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/node bumped from ^2.0.1 to ^2.0.2
</details>

<details><summary>circleci: 2.1.0</summary>

### Features

* implement the new scheduled pipeline config in toolkit circleci hooks ([13ef342](https://github.com/Financial-Times/dotcom-tool-kit/commit/13ef342d62994a833f43c559bf1fc8772c945030))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^2.0.1 to ^2.1.0
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/circleci bumped from ^2.0.1 to ^2.1.0
    * @dotcom-tool-kit/npm bumped from ^2.0.2 to ^2.0.3
</details>

<details><summary>create: 2.0.3</summary>

### Bug Fixes

* error conflict on npm init ([e772760](https://github.com/Financial-Times/dotcom-tool-kit/commit/e772760f26a506e95baa995d998e04622a28bf9d))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
    * dotcom-tool-kit bumped from ^2.1.1 to ^2.2.0
</details>

<details><summary>eslint: 2.1.0</summary>

### Features

* **eslint:** use a peer dependency for eslint ([e16be4d](https://github.com/Financial-Times/dotcom-tool-kit/commit/e16be4da9312f50c3ec617bca3d5418c402c3715))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/webpack bumped from ^2.1.0 to ^2.1.1
</details>

<details><summary>heroku: 2.0.2</summary>

### Bug Fixes

* **heroku:** scale dynos before promoting them to production ([6a3b53a](https://github.com/Financial-Times/dotcom-tool-kit/commit/6a3b53af7c41bab9a6d1cde98729c7751c986856))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^2.0.2 to ^2.0.3
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/vault bumped from ^2.0.1 to ^2.0.2
</details>

<details><summary>@dotcom-tool-kit/jest: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 2.1.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/lint-staged bumped from ^2.1.1 to ^2.1.2
    * @dotcom-tool-kit/options bumped from ^2.0.1 to ^2.0.2
</details>

<details><summary>@dotcom-tool-kit/mocha: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/n-test: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/next-router: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/vault bumped from ^2.0.1 to ^2.0.2
</details>

<details><summary>@dotcom-tool-kit/node: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/vault bumped from ^2.0.1 to ^2.0.2
</details>

<details><summary>@dotcom-tool-kit/nodemon: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/vault bumped from ^2.0.1 to ^2.0.2
</details>

<details><summary>@dotcom-tool-kit/npm: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/options: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.0.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.0.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/secret-squirrel: 1.0.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>types: 2.2.0</summary>

### Features

* add options to pa11y plugin ([7670db7](https://github.com/Financial-Times/dotcom-tool-kit/commit/7670db7f59e9a798b5fc256182534c5c696f700a))
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/vault: 2.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.1 to ^2.0.2
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>@dotcom-tool-kit/webpack: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
</details>

<details><summary>dotcom-tool-kit: 2.2.0</summary>

### Features

* add --listPlugins option ([2db53ca](https://github.com/Financial-Times/dotcom-tool-kit/commit/2db53ca2b14d307644beda46c86114645a1aa285))

### Bug Fixes

* **core:** improve loadToolKitRC typing and defaults ([efc05fb](https://github.com/Financial-Times/dotcom-tool-kit/commit/efc05fb3e0c0abac74d5545d5a10ff18e04439cb))
* move config plugin assignment earlier to prevent race condition ([5beb1a8](https://github.com/Financial-Times/dotcom-tool-kit/commit/5beb1a8c6c8ec6490285e2ea857e1874e0d13efa))
* skip resolving plugins that have been resolved already ([bb51635](https://github.com/Financial-Times/dotcom-tool-kit/commit/bb516357b420619f6a2135323f340ea4a54ad1b7))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.1 to ^2.0.2
    * @dotcom-tool-kit/types bumped from ^2.1.0 to ^2.2.0
  * devDependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.0 to ^2.0.3
    * @dotcom-tool-kit/heroku bumped from ^2.0.0 to ^2.0.2
    * @dotcom-tool-kit/webpack bumped from ^2.0.0 to ^2.1.1
    * @dotcom-tool-kit/babel bumped from ^2.0.0 to ^2.0.2
    * @dotcom-tool-kit/circleci bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/npm bumped from ^2.0.0 to ^2.0.3
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.0 to ^2.0.3
    * @dotcom-tool-kit/frontend-app bumped from ^2.0.0 to ^2.1.1
    * @dotcom-tool-kit/eslint bumped from ^2.0.0 to ^2.1.0
    * @dotcom-tool-kit/mocha bumped from ^2.0.0 to ^2.0.2
    * @dotcom-tool-kit/n-test bumped from ^2.0.0 to ^2.0.2
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by apaleslimghost — CHANGES_REQUESTED** [review]
don't merge this until we've figured out what's going on

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v2.2.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/vault-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v2.1.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v2.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v2.0.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/secret-squirrel-v1.0.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v2.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v2.1.1 :sunflower:

**Pull request merged**
