### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/backend-app: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/npm bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/node bumped from ^2.1.2 to ^2.1.3
</details>

<details><summary>@dotcom-tool-kit/circleci: 2.1.4</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 2.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^2.1.3 to ^2.1.4
    * @dotcom-tool-kit/heroku bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
    * @dotcom-tool-kit/circleci bumped from ^2.1.3 to ^2.1.4
    * @dotcom-tool-kit/npm bumped from ^2.0.6 to ^2.0.7
</details>

<details><summary>@dotcom-tool-kit/create: 2.1.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
    * dotcom-tool-kit bumped from ^2.3.1 to ^2.3.2
</details>

<details><summary>@dotcom-tool-kit/eslint: 2.1.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 2.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/webpack bumped from ^2.1.4 to ^2.1.5
</details>

<details><summary>@dotcom-tool-kit/heroku: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/npm bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
    * @dotcom-tool-kit/vault bumped from ^2.0.5 to ^2.0.6
</details>

<details><summary>husky-npm: 2.2.0</summary>

### Features

* Add commit message hook to husky plugin ([33d862e](https://github.com/Financial-Times/dotcom-tool-kit/commit/33d862e5d6fbb4039e797495435532626522c0bc))
</details>

<details><summary>@dotcom-tool-kit/jest: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 2.1.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/husky-npm bumped from ^2.1.0 to ^2.2.0
    * @dotcom-tool-kit/lint-staged bumped from ^2.1.5 to ^2.1.6
    * @dotcom-tool-kit/options bumped from ^2.0.5 to ^2.0.6
</details>

<details><summary>logger: 2.1.1</summary>

### Bug Fixes

* prevent infinite recursion when logging "[" ([7eb71c2](https://github.com/Financial-Times/dotcom-tool-kit/commit/7eb71c2a0efe56ce9566fc8efa6b916ed0414a75))
</details>

<details><summary>@dotcom-tool-kit/mocha: 2.1.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/n-test: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/next-router: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
    * @dotcom-tool-kit/vault bumped from ^2.0.5 to ^2.0.6
</details>

<details><summary>@dotcom-tool-kit/node: 2.1.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
    * @dotcom-tool-kit/vault bumped from ^2.0.5 to ^2.0.6
</details>

<details><summary>@dotcom-tool-kit/nodemon: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
    * @dotcom-tool-kit/vault bumped from ^2.0.5 to ^2.0.6
</details>

<details><summary>@dotcom-tool-kit/npm: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/options: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.3.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.0.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/secret-squirrel: 1.0.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/types: 2.5.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/vault: 2.0.6</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>@dotcom-tool-kit/webpack: 2.1.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
</details>

<details><summary>dotcom-tool-kit: 2.3.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/logger bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/options bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/types bumped from ^2.5.0 to ^2.5.1
  * devDependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/heroku bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/webpack bumped from ^2.1.4 to ^2.1.5
    * @dotcom-tool-kit/babel bumped from ^2.0.5 to ^2.0.6
    * @dotcom-tool-kit/circleci bumped from ^2.1.3 to ^2.1.4
    * @dotcom-tool-kit/npm bumped from ^2.0.6 to ^2.0.7
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.0.7 to ^2.0.8
    * @dotcom-tool-kit/frontend-app bumped from ^2.1.5 to ^2.1.6
    * @dotcom-tool-kit/eslint bumped from ^2.1.4 to ^2.1.5
    * @dotcom-tool-kit/mocha bumped from ^2.1.2 to ^2.1.3
    * @dotcom-tool-kit/n-test bumped from ^2.1.0 to ^2.1.1
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by ivomurrell — APPROVED** [review]
everybody loves logger

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.3.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.1.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/logger-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v2.5.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/vault-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v2.1.4 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.0.8 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/eslint-v2.1.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v2.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-v2.1.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v2.1.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/n-test-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v2.1.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/pa11y-v0.3.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v2.0.7 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/secret-squirrel-v1.0.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v2.0.6 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v2.1.5 :sunflower:

**Pull request merged**
