### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by next-team**
:robot: I have created a release *beep* *boop*
---

<details><summary>@dotcom-tool-kit/babel: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/backend-app: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.2.0 to ^2.2.1
    * @dotcom-tool-kit/node bumped from ^2.2.4 to ^2.2.5
    * @dotcom-tool-kit/npm bumped from ^2.0.12 to ^2.0.13
    * @dotcom-tool-kit/secret-squirrel bumped from ^1.0.10 to ^1.0.11
</details>

<details><summary>@dotcom-tool-kit/circleci: 3.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/circleci-heroku: 2.2.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci bumped from ^3.0.1 to ^3.0.2
    * @dotcom-tool-kit/heroku bumped from ^2.1.2 to ^2.1.3
</details>

<details><summary>@dotcom-tool-kit/circleci-npm: 3.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
    * @dotcom-tool-kit/circleci bumped from ^3.0.1 to ^3.0.2
    * @dotcom-tool-kit/npm bumped from ^2.0.12 to ^2.0.13
</details>

<details><summary>@dotcom-tool-kit/component: 2.1.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/circleci-npm bumped from ^3.0.1 to ^3.0.2
    * @dotcom-tool-kit/npm bumped from ^2.0.12 to ^2.0.13
    * @dotcom-tool-kit/secret-squirrel bumped from ^1.0.10 to ^1.0.11
</details>

<details><summary>@dotcom-tool-kit/create: 2.4.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
  * devDependencies
    * dotcom-tool-kit bumped from ^2.4.1 to ^2.4.2
</details>

<details><summary>@dotcom-tool-kit/eslint: 2.2.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/frontend-app: 2.1.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/webpack bumped from ^2.1.10 to ^2.1.11
</details>

<details><summary>@dotcom-tool-kit/heroku: 2.1.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/npm bumped from ^2.0.12 to ^2.0.13
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
    * @dotcom-tool-kit/vault bumped from ^2.0.11 to ^2.0.12
</details>

<details><summary>@dotcom-tool-kit/jest: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged: 3.0.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/lint-staged-npm: 2.0.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/lint-staged bumped from ^3.0.1 to ^3.0.2
    * @dotcom-tool-kit/options bumped from ^2.0.11 to ^2.0.12
</details>

<details><summary>@dotcom-tool-kit/mocha: 2.2.1</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/n-test: 2.1.7</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/next-router: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
    * @dotcom-tool-kit/vault bumped from ^2.0.11 to ^2.0.12
</details>

<details><summary>@dotcom-tool-kit/node: 2.2.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
    * @dotcom-tool-kit/vault bumped from ^2.0.11 to ^2.0.12
</details>

<details><summary>@dotcom-tool-kit/nodemon: 2.1.5</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
    * @dotcom-tool-kit/vault bumped from ^2.0.11 to ^2.0.12
</details>

<details><summary>@dotcom-tool-kit/npm: 2.0.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/options: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/pa11y: 0.3.9</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/prettier: 2.1.3</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/secret-squirrel: 1.0.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>types: 2.8.0</summary>

### Features

* **typescript:** add typescript plugin ([0421bdb](https://github.com/Financial-Times/dotcom-tool-kit/commit/0421bdba1f3a56fc8306b8c487433e54b740905c))
</details>

<details><summary>typescript: 1.0.0</summary>

### Features

* **typescript:** add typescript plugin ([0421bdb](https://github.com/Financial-Times/dotcom-tool-kit/commit/0421bdba1f3a56fc8306b8c487433e54b740905c))

### Bug Fixes

* **typescript:** don't block tsc task if watching for file changes ([28e42b0](https://github.com/Financial-Times/dotcom-tool-kit/commit/28e42b054506f1336dab228245a184627dc20975))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.0 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/upload-assets-to-s3: 2.0.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/vault: 2.0.12</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>@dotcom-tool-kit/webpack: 2.1.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
</details>

<details><summary>dotcom-tool-kit: 2.4.2</summary>

### Bug Fixes

* **cli:** fix lodash dependency ([b5b2958](https://github.com/Financial-Times/dotcom-tool-kit/commit/b5b2958e2feef27ef3dad9c3baf10c72b1cfc846))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @dotcom-tool-kit/options bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/types bumped from ^2.7.1 to ^2.8.0
  * devDependencies
    * @dotcom-tool-kit/backend-app bumped from ^2.1.0 to ^2.1.1
    * @dotcom-tool-kit/heroku bumped from ^2.1.2 to ^2.1.3
    * @dotcom-tool-kit/webpack bumped from ^2.1.10 to ^2.1.11
    * @dotcom-tool-kit/babel bumped from ^2.0.11 to ^2.0.12
    * @dotcom-tool-kit/circleci bumped from ^3.0.1 to ^3.0.2
    * @dotcom-tool-kit/npm bumped from ^2.0.12 to ^2.0.13
    * @dotcom-tool-kit/circleci-heroku bumped from ^2.2.0 to ^2.2.1
    * @dotcom-tool-kit/frontend-app bumped from ^2.1.12 to ^2.1.13
    * @dotcom-tool-kit/eslint bumped from ^2.2.4 to ^2.2.5
    * @dotcom-tool-kit/mocha bumped from ^2.2.0 to ^2.2.1
    * @dotcom-tool-kit/n-test bumped from ^2.1.6 to ^2.1.7
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by ivomurrell** [comment]
hmm, since we [upgraded](https://github.com/Financial-Times/dotcom-tool-kit/pull/262) to release-please 15 the changelogs seem to be pulling in changes unrelated to the package even though the versions seem to be correct 🤔 I'll investigate this tomorrow.

**Review by ivomurrell — CHANGES_REQUESTED** [review]
blocked on some behaviour fixes in #345

**Review by ivomurrell — APPROVED** [review]
LGTM now that the fixes have been merged

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/dotcom-tool-kit-v2.4.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/create-v2.4.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/options-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/types-v2.8.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/vault-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/babel-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/backend-app-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-v3.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-heroku-v2.2.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/circleci-npm-v3.0.2 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/component-v2.1.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/eslint-v2.2.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/frontend-app-v2.1.13 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/heroku-v2.1.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/jest-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/lint-staged-npm-v2.0.13 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/mocha-v2.2.1 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/next-router-v2.0.12 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/node-v2.2.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/nodemon-v2.1.5 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/npm-v2.0.13 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/pa11y-v0.3.9 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/prettier-v2.1.3 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/secret-squirrel-v1.0.11 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/typescript-v1.0.0 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/upload-assets-to-s3-v2.0.13 :sunflower:

**Comment by next-team** [comment]
:robot: Release is at https://github.com/Financial-Times/dotcom-tool-kit/releases/tag/webpack-v2.1.11 :sunflower:

**Pull request merged**
